version: "3.9"

services:
  gamestore-db:
    image: postgres
    container_name: gamestore-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gamestore
    ports:
      - "5432:5432"
    volumes:
      - gamestore_data:/var/lib/postgresql/data

volumes:
  gamestore_data:
